version: "3.8"
services:
  samba:
    build:
      context: .
      args:
        SMB_USER: '${SMB_USER}'
        SMB_PASSWD: '${SMB_PASSWD}'
        TZ: '${TZ}'
    ports:
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - /mnt/TimeMachine:/mnt/TimeMachine:z
    restart: unless-stopped
